### PR TITLE
Add debug packages for libs and tools

### PR DESCRIPTION
**Pull request by pdf**
Simply adds the relevant -dbg packages to control, and associated dh_strip override.  Debug packages ought to improve the quality of some bug reports.  Not sure what happened with this the first time around, but these are working fine for me now.

### CODE REVIEW

**Comment by dajhorn** [comment]
A vanilla clone of this branch fails to build:

```
dpkg-deb: building package `libnvpair1' in `../libnvpair1_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libnvpair1-dbg' in `../libnvpair1-dbg_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libuutil1' in `../libuutil1_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libuutil1-dbg' in `../libuutil1-dbg_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libzfs-dev' in `../libzfs-dev_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libzfs1' in `../libzfs1_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libzfs1-dbg' in `../libzfs1-dbg_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `libzpool1' in `../libzpool1_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: error: parsing file 'debian/libzpool1-dbg/DEBIAN/control' near line 7 package 'libzpool1-dbg':
 'Depends' field, reference to 'libzpool1': error in version: epoch in version is not number
dh_builddeb: dpkg-deb --build debian/libzpool1-dbg .. returned exit code 2
dpkg-deb: building package `zfs-dkms' in `../zfs-dkms_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `zfs-initramfs' in `../zfs-initramfs_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `zfsutils' in `../zfsutils_0.6.0.68-0ubuntu1_amd64.deb'.
dpkg-deb: building package `zfsutils-dbg' in `../zfsutils-dbg_0.6.0.68-0ubuntu1_amd64.deb'.
make: *** [binary] Error 1
```

**Comment by pdf** [comment]
Sorry, I cleaned out some warnings before push, accidentally killed a `}`.

**Comment by dajhorn** [comment]
Okay, that works.  I will fold this pull request into a single commit, do some testing, and likely merge it next week.

**Comment by dajhorn** [comment]
I merged the pull request and amended it as follows:
- Fold into a single commit and add a comment.
- Demote the dependencies according to the policy manual.
- Correct the "libnvpar1" typo.

**Pull request closed without merging**
