### PR TITLE
Updated bash completions and sudoers

### PR DESCRIPTION
**Pull request by Aneurin**
I recently realised that my bash completions are being shipped as part of the Debian packages for ZoL, which prompted me to make some updates.

These completions still aren't complete, but they now include full-featured completions for more of the commands (basically any which I use with any regularity in my day job). Existing completions are greatly improved over the original, significantly more useful if you have a lot of snapshots, and somewhat better in the case where you don't have access to /dev/zfs, but _do_ have passwordless sudo set up for read-only commands, as suggested by ZoL.

I'm not sure if you actually use this repo as a working area at all, plus I recognise that having a number of commits for such a small feature might be an inappropriate level of detail, so feel free to ignore the pull request and just grab the file if you prefer.

### CODE REVIEW

**Comment by dajhorn** [comment]
@Aneurin, I merged this into my working snapshot/ubuntu/precise branch for testing. Thanks for the update.

**Comment by FransUrbo** [comment]
@Aneurin could you rebase this against <code>snapshot/debian/wheezy/0.6.3-0.9_g540ce4_wheezy</code>? I've completely missed this one.

**Comment by Aneurin** [comment]
@FransUrbo Er, a couple of months ago I got kind of confused and frustrated by all of the branching in ZoL, and decided that since it's not ZoL specific anyway, I'd keep it separately.

Since it's only one file, your best bet would probably be just to grab the current version from https://github.com/Aneurin/zfs-bash/blob/master/zfs_completion.bash

**Comment by dajhorn** [comment]
@Aneurin, I pulled anuerin/zfs-bash directly into pkg-zfs for Ubuntu and preserved your history here:  zfsonlinux/pkg-zfs@89858d60d6810d582577f0c76de5b1898250f802

Your commits should appear verbatim if you click the parent link.

**Pull request closed without merging**
