### PR TITLE
Add support for systemd systems

### PR DESCRIPTION
**Pull request by benley**
For zfsonlinux/pkg-zfs#145

### CODE REVIEW

**Comment by KaptenJansson** [comment]
I suppose this affects debian as well (essentially any linux dist using systemd)?

**Comment by KaptenJansson** [comment]
Also, could this get some attention? ;)

**Comment by benley** [comment]
I'm pretty sure this is already merged in the ubuntu packages, starting with Trusty.  Not sure about Debian - or why this PR is still open.

**Comment by FransUrbo** [comment]
The Debian GNU/Linux packages have had it "for years", so this is not applicable to Debian GNU/Linux.

**Comment by KaptenJansson** [comment]
So why does it does not automount properly when Debian jumped over to systemd from init?

**Comment by FransUrbo** [comment]
@KaptenJansson As far as I know, it doesn't. Are you saying it doesn't? I have seen no issue about this, so it's hard to fix something that isn't broken (or I don't know is broken)!

**Comment by KaptenJansson** [comment]
Very true;) I will gather data to prove it and file a separate issue. Thanks for the swift response. Oh, as @benley mentioned, this PR should probably be closed ;).

**Comment by dajhorn** [comment]
@KaptenJansson,

> Also, could this get some attention? ;)

Ubuntu is importing ZoL downstream into regular distribution, which should make this kind of work redundant.

NB:
- http://packages.ubuntu.com/source/wily/spl-linux
- http://packages.ubuntu.com/source/wily/zfs-linux

> Oh, as @benley mentioned, this PR should probably be closed ;).

Done.

**Comment by KaptenJansson** [comment]
@dajhorn thanks for the explanation.

**Pull request closed without merging**
