### PR TITLE
fixes for building debian (wheezy) packages from recent zfs git source

### PR DESCRIPTION
**Pull request by bpkroth**
Hi all, here are some patches to the Debian (wheezy) packaging system so that we can build more recent git versions of ZFS on Linux.

Let me know if you have any questions.

Thanks,
Brian

See Also: https://github.com/zfsonlinux/zfs/issues/2863

### CODE REVIEW

**Comment by bpkroth** [comment]
BTW, pkg-spl currently has a merge conflict on the README.markdown between upstream and master/debian/wheezy (when following your directions).  It's pretty trivial to fix so I didn't include a separate pull request for that, but it might affect others trying to build newer git releases in order to test out patches/fixes.

**Comment by FransUrbo** [comment]
I'm sorry, but you've wasted your time. You should have asked first..

Please see https://github.com/zfsonlinux/pkg-zfs/tree/snapshot/debian/wheezy/0.6.3-21_7b2d78_wheezy. Can't get any fresher than that...

**Comment by bpkroth** [comment]
Awesome, though I swear that wasn't there last week.  Thanks so much for your time and help.

Is there a similar snapshot for spl as well?

Thanks,
Brian

Turbo Fredriksson notifications@github.com 2014-11-20 11:43:

**Comment by FransUrbo** [comment]
> Awesome, though I swear that wasn't there last week.

It probably wasn't. I pushed that yesterday I think. But just slightly older have been there for a month or so...

> Is there a similar snapshot for spl as well? 

Yes. Check with 'git tag -l' and then find the one that looks latest.

_currently_ that is:

```
snapshot/debian/wheezy/0.6.3-13_917fef_wheezy=
```

**Comment by bpkroth** [comment]
Turbo Fredriksson notifications@github.com 2014-11-20 12:30:

> > Awesome, though I swear that wasn't there last week.
> 
>   It probably wasn't. I pushed that yesterday I think. But just slightly
>   older have been there for a month or so...

Yeah, the bug we're trying to debug is more recent than that though 
which is why I started down this rabbit hole.

> > Is there a similar snapshot for spl as well?
> 
>   Yes. Check with 'git tag -l' and then find the one that looks latest.

Der, I was looking in the branches view in github.

>   _currently_ that is:
> 
>   snapshot/debian/wheezy/0.6.3-13_917fef_wheezy=

Perfect.  Thanks so much.

Cheers,
Brian

**Comment by bpkroth** [comment]
Brian Kroth bpkroth@gmail.com 2014-11-20 14:40:

> Turbo Fredriksson notifications@github.com 2014-11-20 12:30:
> 
> > > Awesome, though I swear that wasn't there last week.
> > 
> >  It probably wasn't. I pushed that yesterday I think. But just slightly
> >  older have been there for a month or so...
> 
> Yeah, the bug we're trying to debug is more recent than that though 
> which is why I started down this rabbit hole.
> 
> > > Is there a similar snapshot for spl as well?
> > 
> >  Yes. Check with 'git tag -l' and then find the one that looks latest.
> 
> Der, I was looking in the branches view in github.
> 
> >  _currently_ that is:
> > 
> >  snapshot/debian/wheezy/0.6.3-13_917fef_wheezy=
> 
> Perfect.  Thanks so much.
> 
> Cheers,
> Brian

Hate to bug you again, but the build instructions seem to have changed 
somewhat.  Here's what I did, does it seem about right to you?

Thanks,
Brian

Grab the code:

# git clone https://github.com/zfsonlinux/pkg-spl.git

# cd pkg-spl

# git checkout snapshot/debian/wheezy/0.6.3-13_917fef_wheezy

Make a local branch:

# git checkout -b $local_branch_name

Update the git-buildpackage config file with $local_branch_name 
debian-branch and debian-tag:

# sed -i "s|master/debian/wheezy|$local_branch_name|" debian/gbp.conf

Generate the control file (the various debian build scripts all seem to 
error out without this):

# ./debian/rules override_dh_prep-base-deb-files

Build the package with git-buildpackage instead of dpkg-buildpackage 
(since we have no source tarball):

# git-buildpackage -uc -us

Similar for pkg-zfs, except that I had to add dh-systemd to the 
Build-Depends in control.in since it's not installed on wheezy machines 
by default (available in backports though).

**Comment by FransUrbo** [comment]
> Make a local branch: 
> 
> # git checkout -b $local_branch_name

You don't need to do that.

> Update the git-buildpackage config file with $local_branch_name 
> debian-branch and debian-tag: 
> 
> # sed -i "s|master/debian/wheezy|$local_branch_name|" debian/gbp.conf

Nor this (because of the former).

> Build the package with git-buildpackage instead of dpkg-buildpackage 
> (since we have no source tarball): 
> 
> # git-buildpackage -uc -us

I use:

```
git-buildpackage --git-ignore-branch --git-ignore-new
```

But since I sign my packages, you probably need the "-uc -us" as well.

> Similar for pkg-zfs, except that I had to add dh-systemd to the 
> Build-Depends in control.in since it's not installed on wheezy machines 
> by default (available in backports though).

I know. I've missed that part. I have it in a local tag, but I didn't want to do a release
just because of that.

Otherwise, all commands seems just fine.=

**Pull request closed without merging**
